const character = {
  abilities: [[2, 1, 0], [2, 0, 1], [1, 2, 0], [0, 2, 1], [1, 0, 2], [0, 1, 2]],
  features: [
    "attack: add +1 to attack rolls",
    "spell: cast one speel per day",
    "skill: gain advantage on skill related danger rolls"
  ],
  skills: [
    "briarborn: tracking, foragin, survival",
    "fingersmith: tinkering, pocking locks or pockets",
    "roofrunner: climbing, leaping, balancing",
    "shadowjack: moving silently, hiding in shadows"
  ],
  gear: [
    "animal scent",
    "bear trap",
    "bedroll",
    "caltrops",
    "chain",
    "chalk",
    "chisel",
    "crowbar",
    "fishing net",
    "glass marbles",
    "glue",
    "grappling hook",
    "grease",
    "hacksaw",
    "hammer",
    "hand drill",
    "horn",
    "iron spikes",
    "iron tongs",
    "lantern and oil",
    "large sack",
    "lockpicks (3)",
    "manacles",
    "medicine",
    "metal file",
    "rations (3)",
    "rope (50 ft.)",
    "steel wire",
    "shovel",
    "steel mirror",
    "ten foot pole",
    "tinderbox",
    "torch",
    "vial of acid",
    "vial of poison",
    "waterskin"
  ],
  appearances: [
    "aquiline",
    "athletic",
    "barrel-chested",
    "boney",
    "brawney",
    "brutish",
    "bullnecked",
    "chiseled",
    "coltish",
    "corpulent",
    "craggy",
    "delicate",
    "furrowed",
    "gaunt",
    "gorgeous",
    "grizzed",
    "haggard",
    "handsome",
    "hideous",
    "lanky",
    "pudgy",
    "ripped",
    "rosy",
    "scrawny",
    "sinewy",
    "slender",
    "slumped",
    "solid",
    "square-jawed",
    "statuesque",
    "towering",
    "trim",
    "weathered",
    "willowy",
    "wiry",
    "wrinkled"
  ],
  physicalDetails: [
    "acid scars",
    "battle scars",
    "birthmark",
    "braided hair",
    "brand mark",
    "broken nose",
    "bronze skinned",
    "burn scars",
    "bushy eyebrows",
    "curly hair",
    "dark skinned",
    "dreadlocks",
    "exotic accent",
    "flogging scars",
    "freckles",
    "gold tooth",
    "hoarse voice",
    "huge beard",
    "long hair",
    "matted hair",
    "missing ear",
    "mustache",
    "muttonchops",
    "nine fingers",
    "oiled hair",
    "one-eyed",
    "pale skinned",
    "piercings",
    "ritual scars",
    "sallow skin",
    "shaved head",
    "sunburned",
    "tangled hair",
    "tattoos",
    "topknot"
  ],
  backgrounds: [
    "alchemist",
    "beggar-prince",
    "blackmailer",
    "bounty-hunter",
    "chimney sweep",
    "coin-clipper",
    "contortionist",
    "counterfeiter",
    "cultist",
    "cutpurse",
    "debt-collector",
    "deserter",
    "fence",
    "fortuneteller",
    "galley slave",
    "gambler",
    "gravedigger",
    "headsman",
    "hedge knight",
    "highwayman",
    "housebreaker",
    "kidnapper",
    "mad prophet",
    "mountebank",
    "peddler",
    "pit-fighter",
    "poisoner",
    "rat-catcher",
    "scrivener",
    "sellsword",
    "slave",
    "smuggler",
    "street performer",
    "tattooist",
    "urchin",
    "usurer"
  ],
  clothes: [
    "antique",
    "battle-torn",
    "bedraggled",
    "blood-stained",
    "ceremonial",
    "dated",
    "decaying",
    "eccentric",
    "elegant",
    "embroidered",
    "exotic",
    "fashionable",
    "flamboyant",
    "food-stained",
    "formal",
    "frayed",
    "frumpy",
    "garish",
    "grimy",
    "haute couture",
    "lacey",
    "livery",
    "mud-stained",
    "ostentatious",
    "oversized",
    "patched",
    "patterned",
    "perfumed",
    "practical",
    "rumpled",
    "sigils",
    "singed",
    "tasteless",
    "undersized",
    "wine-stained",
    "worn out"
  ],
  personalities: [
    "bitter",
    "brave",
    "cautious",
    "chipper",
    "contrary",
    "cowardly",
    "cunning",
    "driven",
    "entitled",
    "gregarious",
    "grumpy",
    "heartless",
    "honor-bound",
    "hotheaded",
    "inquisitive",
    "irascible",
    "jolly",
    "know-it-all",
    "lazy",
    "loyal",
    "menacing",
    "mopey",
    "nervous",
    "protective",
    "righteous",
    "rude",
    "sarcastic",
    "savage",
    "scheming",
    "spacey",
    "stoic",
    "stubborn",
    "stuck-up",
    "suspicious",
    "wisecracking"
  ],
  mannerisms: [
    "anecdotes",
    "breathy",
    "chuckles",
    "clipped",
    "cryptic",
    "deep voice",
    "drawl",
    "enunciates",
    "flowery speech",
    "gravelly voice",
    "highly formal",
    "hypnotic",
    "interrupts",
    "laconic",
    "laughs",
    "long pauses",
    "melodious",
    "monotone",
    "mumbles",
    "narrates",
    "overly casual",
    "quaint sayings",
    "rambles",
    "random facts",
    "rapid-fire",
    "rhyming",
    "robotic",
    "slow speech",
    "speechifies",
    "squeaky",
    "street slang",
    "stutters",
    "talks to self",
    "trails off",
    "very loud",
    "whispers"
  ],
  weapons: [
    [
      ["axe", "dagger", "mace", "short sword", "flail", "one-handed spear"],
      ["spear", "halberd", "long sword", "warhammer"],
      ["bow", "crossbow", "sling"]
    ],
    ["1 hand", "+1 damage, 2 hands", "2 hands"]
  ]
};

export default character;
